CREATE TABLE IF NOT EXISTS person
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text                                             NOT NULL,
    age  int CHECK (age > 0)
);

CREATE TABLE IF NOT EXISTS book
(
    id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     text                                             NOT NULL,
    author    text                                             NOT NULL,
    year      int CHECK (year > 1900)                          NOT NULL,
    person_id int REFERENCES person (id)
);